### ISSUE TITLE
SDK 3.4.1+ Incompatibility

### ISSUE THREAD

**Issue by rhaamo** [BocuD/VRChatApiTools#10]
Hello,

On SDK 3.4.1 and newer I get the following error:

```
Packages\com.bocud.vrcapitools\Editor\VRChatApiToolsEditor.cs(125,26): error CS0117: 'ApiWorld' does not contain a definition for 'SortHeading'
```

In my SDK (3.5.0-beta.1 and another in 3.4.1) it is just replaced by `"updated"`, changing that code line seems to pass.

**Comment by BocuD** [comment]
This was patched using above change. While this does make buildhelper usable, i won't be doing any release until i have time to properly rework the tool to no longer use my custom uploader, but rather the one that is now provided by VRC.
